name: DNS Sync Changes
on: 
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  apply_dns:
    runs-on: ubuntu-latest
    environment: DNS
    steps: 
      - uses: actions/checkout@v3
      - env:
          HETZNER_APIKEY: ${{ secrets.HETZNER_APIKEY }}
        run: |
          docker run -e HETZNER_APIKEY="${HETZNER_APIKEY}" --rm -v $(pwd):/dns stackexchange/dnscontrol check
          docker run -e HETZNER_APIKEY="${HETZNER_APIKEY}" --rm -v $(pwd):/dns stackexchange/dnscontrol preview
          docker run -e HETZNER_APIKEY="${HETZNER_APIKEY}" --rm -v $(pwd):/dns stackexchange/dnscontrol push